Add `PaCMAP` to Seurat-Wrappers
satijalab/seurat-wrappers pull request #202
Opened 2024-10-10 17:37 UTC by hyhuang00

Dear Seurat-wrappers Developers,

We would like to add the `PaCMAP` algorithm to the Seurat Wrappers. This PR implements the `RunPaCMAP()` wrapper for the `PaCMAP` algorithm. The original implementation of the algorithm can be found at [the current official repository](https://github.com/YingfanWang/PaCMAP). A detailed study on PaCMAP on scRNA-seq data can be found in [our paper](https://www.nature.com/articles/s42003-022-03628-x).

Best,
Yiyang Sun, Haiyang Huang, Gaurav Rajesh Parikh, Cynthia Rudin

2024-11-20 16:33 UTC, dcollins15 requested changes
Thanks for the fantastic tool and the excellent PR! This is shaping up to be a great addition to `SeuratWrappers` 🔥 

I've got a few small tweaks for you, but generally, things are looking very clean—the main ToDos are:

1. Updating the `Version` and `Date` fields in the package's `DESCRIPTION` file to `0.4.0` and today's date respectively. 
2. Regenerating the package's man/*.Rd files — see [Roxygen2's documentation](https://roxygen2.r-lib.org/) for guidance.

Once those updates are taken care of, this should be good to go 🚀 

One optional sugggestion:

Currently, the vignette includes only one example of `RunPaCMAP` using the `features` parameter. It might be helpful for users if you add an example demonstrating its usage with the `dims` parameter as well.

---

@rsatija Just flagging that we're almost certainly going to have to update this vignette before we're able to get the `test-vignettes` check back up and running for this repo. If we'd like to take the opportunity to come up with a proper solution for resolving `python` dependencies, this would probably also benefit folks running `scVI` 🤔

2024-11-20 16:33 UTC, dcollins15 commented on R/pacmap.R
> +#' @param ... Additional arguments to be passed to the pacmap.PaCMAP function.
It's best to document parameters that are shared across all implementations (i.e., those explicitly in the method signature) in the generic function.

For example:

- Keep the description of the object parameter in the generic.
- Fully document the parameters for RunPaCMAP.default.
- Document Seurat-specific parameters in RunPaCMAP.Seurat.

2024-11-20 22:07 UTC, hyhuang00 commented
Hi David,

Thank you so much for your prompt review and useful advice regarding our code! Yiyang and I have made some changes accordingly. Major changes include:
- We've added a new warning message whem both `assay` and `dims` are specified.
- We separated the documentation to each function.
- We added an example in case `dims` are specified.
- We updated the `NAMESPACE` and `DESCRIPTION` via `roxygen::roxygenize()`.

Please let us know if further changes are needed!

2024-11-21 18:15 UTC, dcollins15 approved these changes
LGTM 🚀

2024-11-21 18:16 UTC, merged

2024-11-21 19:08 UTC, hyhuang00 commented
Apologies for opening a new pull request. We realized that the README update for the added method was overlooked in this PR. PR (#206) includes the missing documentation. Thank you again for your prompt review and help!